#!/bin/bash
#
#       /etc/rc.d/init.d/LiberatorAdventuresd
#
#       starts Liberator Adventures Blog
#
# chkconfig: - 20 80
# description:	A blog about adventures on SWGEmu's Liberator Server
# processname: LiberatorAdventuresd
# config: /usr/local/etc/LiberatorAdventured.conf
# pidfile: /var/run/LiberatorAdventuresd/LiberatorAdventuresd.pid

# Source function library.

. /lib/lsb/init-functions
. /etc/rc.d/init.d/functions

prog=LiberatorAdventuresd
lockfile=/var/lock/subsys/LiberatorAdventuresd
RETVAL=0
INIFILE=/usr/local/etc/LiberatorAdventuresd.conf
MY_USER=LiberatorAdventures
MY_GROUP=LiberatorAdventures
LIBADV_PIDFILE=/var/run/LiberatorAdventures/LiberatorAdventures.pid
LIBADV_OPTS="-conf $INIFILE"
pidfile=$LIBADV_PIDFILE

start() {
        echo -n "Starting LiberatorAdventuresd: "
	start_daemon -u $MY_USER -p $pidfile $prog  $LIBADV_OPTS
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
		touch "$lockfile" && success || failure
	fi
	echo
}

stop() {
        echo -n "Shutting down LiberatorAdventuresd: "
	killproc $prog -INT
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
		/bin/rm "$lockfile" "$pidfile" 2> /dev/null && success || failure
	fi
	echo
}

restart() {
	stop
	start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
	status $prog
	RETVAL=$?	
        ;;
    restart|force-reload)
	restart
        ;;
    reload)
        ;;
    condrestart)
        [ -f "$lockfile" ] && restart
	;;
    *)
        echo "Usage: <servicename> {start|stop|status|restart|reload|force-reload|condrestart}"
        exit 1
        ;;
esac
exit $RETVAL
