#! /bin/sh
# /etc/init.d/blah
#

# Some things that run always
touch /var/lock/blah

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting LiberatorAdventuresd "
    LiberatorAdventuresd -config /usr/local/etc/LiberatorAdventuresd.conf
    ;;
  stop)
    echo "Not Stopping LiberatorAdventuresd "
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop}"
    exit 1
    ;;
esac

exit 0
